### ISSUE TITLE
Error predicting on custom data

### ISSUE THREAD

**Issue by ericleonardo** [clementetienam/Ultra-Fast-Mixture-of-Experts-Regression#1]
[BinaryClass.zip](https://github.com/clementetienam/Ultra-Fast-Mixture-of-Experts-Regression/files/7636953/BinaryClass.zip)
Hi, Dr Clement!
If I run your code on my own data, it returns error when running **Predicting.m** code (but **Training.m** is ok).
I replaced original data by commenting "load" and putting X and yb manually with my data for binary classification:

```
 %load('jm_data.mat')
 %yb=[ptotped, betanped, wped];
 %X=[r a kappa delta bt ip neped betan zeffped];
```

Error when running Predicting.m (after successful Training):

```
Error using Unseen_soft_1 (line 18)
Dot indexing is not supported for variables of this type.

Error in Forwarding (line 44)
[Softmean(:,ii),~]=Unseen_soft_1(Regressors{ii,1},...

Error in PREDICTING (line 96)
[Hardmean,Softmean]=Forwarding(X_test2,f,...
```

My binary class data is: X (20000, 4), Y (20000, 1)
Option 1: 1-Mixture of Experts model -GP experts and DNN gate
Option 2: 2-CCR-MM
Option 3: Maximum iteration: 3
Option 4: 1-Recommended number of Experts
Matlab R2021b

Please, how can I solve this error predicting on my own data?
I'm trying to increase accuracy on my binary classification task, maybe this mixture of experts works...
Despite your code is for Regression, I use regression for binary classification by: results >0.5 class 1, and <0.5 class 0.

Thank you for sharing this great tool!
My data is attached.. if you could try it...

**Comment by clementetienam** [comment]
Hi, MoE is mainly used for regression tasks. The Gate gives the probabilities of each data associated with a particular convex hull in training. The Gate is basically a soft max probability ( or some probability associated when learning the classifier). Each independent regressor is then used to learn each member associated to that expert. The cost functional during regression is an MSE, for your classification case, you can change it to a binary cross-entropic loss. This is counterintuitive, as you have a bigger classifier that acts as a general gate, and a smaller classifier to focus on the different regions or experts. you are better of using SMOTE if you have unbalanced classes or you could still go ahead with this logic. Build a classifier for your original data set (you get the labels for this classifier from activating K-means clustering on the [X,y] pair), then use this classifier to get the segmented experts. for each expert, build independent classifiers for each expert. During inference, predict with Xtest, i.e ytest =f_big(Xtest), where ftest, is the "Big classifier", use the independent classifiers to get the sub-class. Watch this, assume you do stage 1 and you get 2 classes, call it Class 1, Clas2, (this machine is f_big) you then build independent classes for Class 1, assume 3 classes (this machine is f_1), we will have Class1_1, Class1_2, Class1_3 and for Clas 2 we have 2 classes (this machine is f_2), call it Clas2_1 and Clas2_2, during inference, do ytest =f_big(Xtest), then do : if ytest ==1, final = f_1(Xtest) else final =f_2(Xtest), your final test (assuming class 1) will be f_1(f_big(Xtest))  or f_1 o f_big (X-test). This is a hard classification MoE.  you could say for the example above we have "5 classes" as you split the original 2 class problem into sub class 3 and 2 respectively. Hope this helps.

**Comment by ericleonardo** [comment]
Thank you! Very interesting your suggestion! I will try it...
But is that error message related to my Y data being binary 1/0?

```
Error using Unseen_soft_1 (line 18)
Dot indexing is not supported for variables of this type.
```

I'm used to make binary classification using Regression algorithms (Linear Regression, etc).
As results are between 0 and 1, consider as class 1 if result is >0.5, and class 0 for results <0.5.
It is even better because I can increase accuracy by filtering: class 1 if result is >0.55, class 0 if it is <0.45.
It was that way of doing Regression and interpreting results by threshold that I would use your code for classification.
